; This is an auto-generated header file from the build.sh script

STAGE2_SECTORS equ 8 
MEMORY_MAP_ADDRESS equ 0x7000 

MEMORY_MAP_ENTRY_COUNT_ADDRESS equ 0x6FF8

KERNEL_MAIN_LBA equ 9
KERNEL_MAIN_SECTORS equ 83
KERNEL_MAIN_LOAD_ADDR equ 0x100000

TEMP_KERNEL_MAIN_LOAD_ADDR equ 0x10000
